2019-10-15 15:54:51,199 ERROR 14356 [-/::1/-/50ms POST /api/login] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'userName' in 'where clause'
    at Query.Sequence._packetToError (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    --------------------
    at Pool.query (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\exerciseCode\js\node\egg-example\node_modules\co\index.js:65:19)
    at F:\exerciseCode\js\node\egg-example\node_modules\co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `userName` = 'aaaTest' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'userName' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `userName` = 'aaaTest' AND `password` = '123456' LIMIT 0, 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 14356
hostname: PC-201903022055

2019-10-15 15:55:03,279 ERROR 14356 [-/::1/-/6ms POST /api/login] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'userName' in 'where clause'
    at Query.Sequence._packetToError (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    --------------------
    at Pool.query (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\exerciseCode\js\node\egg-example\node_modules\co\index.js:65:19)
    at F:\exerciseCode\js\node\egg-example\node_modules\co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `userName` = 'aaaTest' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'userName' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `userName` = 'aaaTest' AND `password` = '123456' LIMIT 0, 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 14356
hostname: PC-201903022055

2019-10-15 17:30:22,763 ERROR 12632 [egg-redis] client error: Error: read ECONNRESET
2019-10-15 17:30:22,781 ERROR 12632 nodejs.ECONNRESETError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "ECONNRESETError"
pid: 12632
hostname: PC-201903022055

2019-10-15 17:30:23,843 ERROR 12632 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2019-10-15 17:30:23,846 ERROR 12632 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 12632
hostname: PC-201903022055

2019-10-15 17:30:24,951 ERROR 12632 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2019-10-15 17:30:24,952 ERROR 12632 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 12632
hostname: PC-201903022055

2019-10-15 17:30:26,104 ERROR 12632 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2019-10-15 17:30:26,105 ERROR 12632 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 12632
hostname: PC-201903022055

2019-10-15 17:30:27,307 ERROR 12632 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2019-10-15 17:30:27,308 ERROR 12632 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 12632
hostname: PC-201903022055

2019-10-15 17:30:28,561 ERROR 12632 [egg-redis] client error: Error: connect ECONNREFUSED 127.0.0.1:6379
2019-10-15 17:30:28,562 ERROR 12632 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 12632
hostname: PC-201903022055

2019-10-17 17:11:57,442 ERROR 14248 [-/::1/-/37ms POST /api/user/info] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (F:\exerciseCode\js\node\egg-example\node_modules\koa\lib\application.js:255:15)
    at handleResponse (F:\exerciseCode\js\node\egg-example\node_modules\koa\lib\application.js:161:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 14248
hostname: PC-201903022055

2019-10-18 09:21:06,803 ERROR 8660 [-/::1/-/39ms POST /api/user/info] nodejs.TypeError: Cannot read property 'find' of undefined
    at UserController.userInfo (F:\exerciseCode\js\node\egg-example\app\controller\user\index.js:8:38)
    at Object.callFn (F:\exerciseCode\js\node\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\exerciseCode\js\node\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:44:32)
    at next (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:45:18)
    at F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:44:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 8660
hostname: PC-201903022055

2019-10-18 09:22:39,517 ERROR 8368 [-/::1/-/38ms POST /api/user/info] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.userInfo (F:\exerciseCode\js\node\egg-example\app\controller\user\index.js:8:39)
    at Object.callFn (F:\exerciseCode\js\node\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\exerciseCode\js\node\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:44:32)
    at next (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:45:18)
    at F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:44:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 8368
hostname: PC-201903022055

2019-10-18 09:22:41,698 ERROR 8368 [-/::1/-/3ms POST /api/user/info] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.userInfo (F:\exerciseCode\js\node\egg-example\app\controller\user\index.js:8:39)
    at Object.callFn (F:\exerciseCode\js\node\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (F:\exerciseCode\js\node\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:44:32)
    at next (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:45:18)
    at F:\exerciseCode\js\node\egg-example\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:44:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 8368
hostname: PC-201903022055

2019-10-18 09:24:28,743 ERROR 2132 [-/::1/-/45ms POST /api/user/info] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'react_template.user' doesn't exist
    at Query.Sequence._packetToError (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    --------------------
    at Pool.query (F:\exerciseCode\js\node\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (F:\exerciseCode\js\node\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (F:\exerciseCode\js\node\egg-example\node_modules\co\index.js:65:19)
    at F:\exerciseCode\js\node\egg-example\node_modules\co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `id` IS NULL LIMIT 0, 1
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'react_template.user' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `user` WHERE `id` IS NULL LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 2132
hostname: PC-201903022055

2019-10-25 13:41:08,614 ERROR 7668 nodejs.ClusterClientNoResponseError: client no response in 3804377ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7668
hostname: PC-201903022055

2019-10-26 16:32:25,266 ERROR 4380 [-/::1/-/50ms POST /api/menu/query] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (F:\exerciseCode\js\node\egg-example\node_modules\koa\lib\application.js:255:15)
    at handleResponse (F:\exerciseCode\js\node\egg-example\node_modules\koa\lib\application.js:161:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 4380
hostname: PC-201903022055

2019-10-28 10:16:49,588 ERROR 2384 [-/::1/-/229ms POST /api/menu/query] nodejs.TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at respond (F:\exerciseCode\js\node\egg-example\node_modules\koa\lib\application.js:255:15)
    at handleResponse (F:\exerciseCode\js\node\egg-example\node_modules\koa\lib\application.js:161:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 2384
hostname: PC-201903022055

2019-10-28 15:16:41,660 ERROR 856 nodejs.EPERMError: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
errno: -4048
syscall: "watch"
code: "EPERM"
filename: null
dir: "F:\\exerciseCode\\js\\node\\egg-example\\app\\service\\menu\\childMenu"
name: "EPERMError"
pid: 856
hostname: PC-201903022055

2019-10-28 15:16:47,702 ERROR 856 nodejs.EPERMError: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
errno: -4048
syscall: "watch"
code: "EPERM"
filename: null
dir: "F:\\exerciseCode\\js\\node\\egg-example\\app\\controller\\menu\\childMenu"
name: "EPERMError"
pid: 856
hostname: PC-201903022055

2019-10-30 09:20:27,863 ERROR 3616 nodejs.ReferenceError: ctx is not defined
    at queryArr.forEach (F:\exerciseCode\js\node\egg-example\app\controller\role\configAuth\index.js:17:19)
    at Array.forEach (<anonymous>)
    at RoleConfigAuthController.arrLength (F:\exerciseCode\js\node\egg-example\app\controller\role\configAuth\index.js:6:14)
    at RoleConfigAuthController.index (F:\exerciseCode\js\node\egg-example\app\controller\role\configAuth\index.js:63:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 3616
hostname: PC-201903022055

2019-10-30 09:20:27,866 ERROR 3616 nodejs.ReferenceError: ctx is not defined
    at queryArr.forEach (F:\exerciseCode\js\node\egg-example\app\controller\role\configAuth\index.js:17:19)
    at Array.forEach (<anonymous>)
    at RoleConfigAuthController.arrLength (F:\exerciseCode\js\node\egg-example\app\controller\role\configAuth\index.js:6:14)
    at RoleConfigAuthController.index (F:\exerciseCode\js\node\egg-example\app\controller\role\configAuth\index.js:63:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

pid: 3616
hostname: PC-201903022055

2019-11-16 14:22:55,579 ERROR 9756 nodejs.ClusterClientNoResponseError: client no response in 4369567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 9756
hostname: PC-201903022055

2019-11-17 09:50:02,618 ERROR 9756 nodejs.ClusterClientNoResponseError: client no response in 63746819ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 9756
hostname: PC-201903022055

2019-11-17 14:41:46,600 ERROR 9756 nodejs.ClusterClientNoResponseError: client no response in 5586200ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 9756
hostname: PC-201903022055

2019-11-17 18:22:50,968 ERROR 9756 nodejs.ClusterClientNoResponseError: client no response in 11424269ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 9756
hostname: PC-201903022055

2019-11-23 13:39:04,814 ERROR 18512 nodejs.ClusterClientNoResponseError: client no response in 388468ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 18512
hostname: PC-201903022055

2019-11-25 14:33:02,648 ERROR 10664 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 10664
hostname: PC-201903022055

2019-11-25 15:44:03,047 ERROR 6768 nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>TypeError: Object of type WeiboRecord is not JSON serializable // Werkzeug Debugger</title>\n    <link rel=\"stylesheet\" href=\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\"\n        type=\"text/css\">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application " ...skip... "strator\\appdata\\local\\programs\\python\\python37\\Lib\\json\\encoder.py\", line 438, in _iterencode\n    o = _default(o)\n  File \"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\json\\__init__.py\", line 100, in default\n    return _json.JSONEncoder.default(self, o)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\Lib\\json\\encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type WeiboRecord is not JSON serializable\n\n-->\n"), POST http://localhost:5000/weibo/capture 500 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"localhost:5000:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:44:03 GMT"}
headers: {"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:44:03 GMT"}
    at JSON.parse (<anonymous>)
    at parseJSON (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:1153:24)
    at F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:883:23
    at decodeContent (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:690:14)
    at IncomingMessage.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:864:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "JSONResponseFormatError"
data: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>TypeError: Object of type WeiboRecord is not JSON serializable // Werkzeug Debugger</title>\n    <link rel=\"stylesheet\" href=\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\"\n        type=\"text/css\">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application state. -->\n    <link rel=\"shortcut icon\"\n        href=\"?__debugger__=yes&amp;cmd=resource&amp;f=console.png\">\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js\"></script>\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js\"></script>\n    <script type=\"text/javascript\">\n      var TRACEBACK = 2483365888632,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = \"kCWOQGyVD7uhkBVvoYRd\";\n    </script>\n  </head>\n  <body style=\"background-color: #fff\">\n    <div class=\"debugger\">\n<h1>TypeError</h1>\n<div class=\"detail\">\n  <p class=\"errormsg\">TypeError: Object of type WeiboRecord is not JSON serializable</p>\n</div>\n<h2 class=\"traceback\">Traceback <em>(most recent call last)</em></h2>\n<div class=\"traceback\">\n  \n  <ul><li><div class=\"frame\" id=\"frame-2483366883512\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2463</em>,\n      in <code class=\"function\">__call__</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def __call__(self, environ, start_response):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>WSGI application. This calls :meth:`wsgi_app` which can be</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>wrapped to applying middleware.&quot;&quot;&quot;</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.wsgi_app(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>def __repr__(self):</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>return &quot;&lt;%s %r&gt;&quot; % (self.__class__.__name__, self.name)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883680\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2449</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>return response(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>finally:</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883568\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask_cors\\extension.py\"</cite>,\n      line <em class=\"line\">161</em>,\n      in <code class=\"function\">wrapped_function</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span># Wrap exception handlers with cross_origin</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span># These error handlers will still respect the behavior of the route</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if options.get('intercept_exceptions', True):</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>def _after_request_decorator(f):</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>def wrapped_function(*args, **kwargs):</pre>\n<pre class=\"line current\"><span class=\"ws\">                    </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>return wrapped_function</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>if hasattr(app, 'handle_exception'):</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>app.handle_exception = _after_request_decorator(</pre>\n<pre class=\"line after\"><span class=\"ws\">                    </span>app.handle_exception)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366887096\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1866</em>,\n      in <code class=\"function\">handle_exception</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span># if we want to repropagate the exception, we can attempt to</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># raise it with the whole traceback in case we can do that</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># (the function was actually called from the except part)</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># otherwise, we just raise the error again</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if exc_value is e:</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>reraise(exc_type, exc_value, tb)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise e</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>self.log_exception((exc_type, exc_value, tb))</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>server_error = InternalServerError()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883624\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\_compat.py\"</cite>,\n      line <em class=\"line\">39</em>,\n      in <code class=\"function\">reraise</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">    </span>import collections.abc as collections_abc</pre>\n<pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def reraise(tp, value, tb=None):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if value.__traceback__ is not tb:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>raise value.with_traceback(tb)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>raise value</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>implements_to_string = _identity</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\"></span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>iterkeys = lambda d: d.iterkeys()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883904\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2446</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span>ctx = self.request_context(environ)</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>error = None</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366886648\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1952</em>,\n      in <code class=\"function\">full_dispatch_request</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>rv = self.preprocess_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if rv is None:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>rv = self.dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>rv = self.handle_user_exception(e)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.finalize_request(rv)</pre>\n<pre class=\"l...(32732)"
path: "/weibo/capture"
status: 500
headers: {"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:44:03 GMT"}
res: {"status":500,"statusCode":500,"statusMessage":"INTERNAL SERVER ERROR","headers":{"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:44:03 GMT"},"size":32732,"aborted":false,"rt":240,"keepAliveSocket":false,"data":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>TypeError: Object of type WeiboRecord is not JSON serializable // Werkzeug Debugger</title>\n    <link rel=\"stylesheet\" href=\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\"\n        type=\"text/css\">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application state. -->\n    <link rel=\"shortcut icon\"\n        href=\"?__debugger__=yes&amp;cmd=resource&amp;f=console.png\">\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js\"></script>\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js\"></script>\n    <script type=\"text/javascript\">\n      var TRACEBACK = 2483365888632,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = \"kCWOQGyVD7uhkBVvoYRd\";\n    </script>\n  </head>\n  <body style=\"background-color: #fff\">\n    <div class=\"debugger\">\n<h1>TypeError</h1>\n<div class=\"detail\">\n  <p class=\"errormsg\">TypeError: Object of type WeiboRecord is not JSON serializable</p>\n</div>\n<h2 class=\"traceback\">Traceback <em>(most recent call last)</em></h2>\n<div class=\"traceback\">\n  \n  <ul><li><div class=\"frame\" id=\"frame-2483366883512\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2463</em>,\n      in <code class=\"function\">__call__</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def __call__(self, environ, start_response):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>WSGI application. This calls :meth:`wsgi_app` which can be</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>wrapped to applying middleware.&quot;&quot;&quot;</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.wsgi_app(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>def __repr__(self):</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>return &quot;&lt;%s %r&gt;&quot; % (self.__class__.__name__, self.name)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883680\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2449</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>return response(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>finally:</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883568\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask_cors\\extension.py\"</cite>,\n      line <em class=\"line\">161</em>,\n      in <code class=\"function\">wrapped_function</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span># Wrap exception handlers with cross_origin</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span># These error handlers will still respect the behavior of the route</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if options.get('intercept_exceptions', True):</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>def _after_request_decorator(f):</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>def wrapped_function(*args, **kwargs):</pre>\n<pre class=\"line current\"><span class=\"ws\">                    </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>return wrapped_function</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>if hasattr(app, 'handle_exception'):</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>app.handle_exception = _after_request_decorator(</pre>\n<pre class=\"line after\"><span class=\"ws\">                    </span>app.handle_exception)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366887096\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1866</em>,\n      in <code class=\"function\">handle_exception</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span># if we want to repropagate the exception, we can attempt to</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># raise it with the whole traceback in case we can do that</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># (the function was actually called from the except part)</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># otherwise, we just raise the error again</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if exc_value is e:</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>reraise(exc_type, exc_value, tb)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise e</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>self.log_exception((exc_type, exc_value, tb))</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>server_error = InternalServerError()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883624\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\_compat.py\"</cite>,\n      line <em class=\"line\">39</em>,\n      in <code class=\"function\">reraise</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">    </span>import collections.abc as collections_abc</pre>\n<pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def reraise(tp, value, tb=None):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if value.__traceback__ is not tb:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>raise value.with_traceback(tb)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>raise value</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>implements_to_string = _identity</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\"></span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>iterkeys = lambda d: d.iterkeys()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366883904\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2446</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span>ctx = self.request_context(environ)</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>error = None</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2483366886648\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1952</em>,\n      in <code class=\"function\">full_dispatch_request</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>rv = self.preprocess_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if rv is None:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>rv = self.dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>rv = self.handle_user_exception(e)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.finalize_request(rv)</pre>\n<pre class=\"l...(32732)","requestUrls":["http://localhost:5000/weibo/capture"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":5000,"socketHandledRequests":1,"socketHandledResponses":1}
pid: 6768
hostname: PC-201903022055

2019-11-25 15:45:07,773 ERROR 6768 nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>TypeError: Object of type WeiboRecord is not JSON serializable // Werkzeug Debugger</title>\n    <link rel=\"stylesheet\" href=\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\"\n        type=\"text/css\">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application " ...skip... "strator\\appdata\\local\\programs\\python\\python37\\Lib\\json\\encoder.py\", line 438, in _iterencode\n    o = _default(o)\n  File \"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\json\\__init__.py\", line 100, in default\n    return _json.JSONEncoder.default(self, o)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\Lib\\json\\encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type WeiboRecord is not JSON serializable\n\n-->\n"), POST http://localhost:5000/weibo/capture 500 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"localhost:5000:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:45:07 GMT"}
headers: {"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:45:07 GMT"}
    at JSON.parse (<anonymous>)
    at parseJSON (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:1153:24)
    at F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:883:23
    at decodeContent (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:690:14)
    at IncomingMessage.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:864:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "JSONResponseFormatError"
data: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>TypeError: Object of type WeiboRecord is not JSON serializable // Werkzeug Debugger</title>\n    <link rel=\"stylesheet\" href=\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\"\n        type=\"text/css\">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application state. -->\n    <link rel=\"shortcut icon\"\n        href=\"?__debugger__=yes&amp;cmd=resource&amp;f=console.png\">\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js\"></script>\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js\"></script>\n    <script type=\"text/javascript\">\n      var TRACEBACK = 2455154541120,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = \"4VpDuv45Xp1Qs2gguCUI\";\n    </script>\n  </head>\n  <body style=\"background-color: #fff\">\n    <div class=\"debugger\">\n<h1>TypeError</h1>\n<div class=\"detail\">\n  <p class=\"errormsg\">TypeError: Object of type WeiboRecord is not JSON serializable</p>\n</div>\n<h2 class=\"traceback\">Traceback <em>(most recent call last)</em></h2>\n<div class=\"traceback\">\n  \n  <ul><li><div class=\"frame\" id=\"frame-2455155536000\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2463</em>,\n      in <code class=\"function\">__call__</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def __call__(self, environ, start_response):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>WSGI application. This calls :meth:`wsgi_app` which can be</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>wrapped to applying middleware.&quot;&quot;&quot;</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.wsgi_app(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>def __repr__(self):</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>return &quot;&lt;%s %r&gt;&quot; % (self.__class__.__name__, self.name)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536168\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2449</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>return response(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>finally:</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536056\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask_cors\\extension.py\"</cite>,\n      line <em class=\"line\">161</em>,\n      in <code class=\"function\">wrapped_function</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span># Wrap exception handlers with cross_origin</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span># These error handlers will still respect the behavior of the route</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if options.get('intercept_exceptions', True):</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>def _after_request_decorator(f):</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>def wrapped_function(*args, **kwargs):</pre>\n<pre class=\"line current\"><span class=\"ws\">                    </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>return wrapped_function</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>if hasattr(app, 'handle_exception'):</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>app.handle_exception = _after_request_decorator(</pre>\n<pre class=\"line after\"><span class=\"ws\">                    </span>app.handle_exception)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155539584\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1866</em>,\n      in <code class=\"function\">handle_exception</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span># if we want to repropagate the exception, we can attempt to</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># raise it with the whole traceback in case we can do that</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># (the function was actually called from the except part)</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># otherwise, we just raise the error again</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if exc_value is e:</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>reraise(exc_type, exc_value, tb)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise e</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>self.log_exception((exc_type, exc_value, tb))</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>server_error = InternalServerError()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536112\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\_compat.py\"</cite>,\n      line <em class=\"line\">39</em>,\n      in <code class=\"function\">reraise</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">    </span>import collections.abc as collections_abc</pre>\n<pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def reraise(tp, value, tb=None):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if value.__traceback__ is not tb:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>raise value.with_traceback(tb)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>raise value</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>implements_to_string = _identity</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\"></span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>iterkeys = lambda d: d.iterkeys()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536392\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2446</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span>ctx = self.request_context(environ)</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>error = None</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536672\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1952</em>,\n      in <code class=\"function\">full_dispatch_request</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>rv = self.preprocess_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if rv is None:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>rv = self.dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>rv = self.handle_user_exception(e)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.finalize_request(rv)</pre>\n<pre class=\"l...(32732)"
path: "/weibo/capture"
status: 500
headers: {"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:45:07 GMT"}
res: {"status":500,"statusCode":500,"statusMessage":"INTERNAL SERVER ERROR","headers":{"content-type":"text/html; charset=utf-8","x-xss-protection":"0","connection":"close","server":"Werkzeug/0.16.0 Python/3.7.0","date":"Mon, 25 Nov 2019 07:45:07 GMT"},"size":32732,"aborted":false,"rt":141,"keepAliveSocket":false,"data":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>TypeError: Object of type WeiboRecord is not JSON serializable // Werkzeug Debugger</title>\n    <link rel=\"stylesheet\" href=\"?__debugger__=yes&amp;cmd=resource&amp;f=style.css\"\n        type=\"text/css\">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application state. -->\n    <link rel=\"shortcut icon\"\n        href=\"?__debugger__=yes&amp;cmd=resource&amp;f=console.png\">\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js\"></script>\n    <script src=\"?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js\"></script>\n    <script type=\"text/javascript\">\n      var TRACEBACK = 2455154541120,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = \"4VpDuv45Xp1Qs2gguCUI\";\n    </script>\n  </head>\n  <body style=\"background-color: #fff\">\n    <div class=\"debugger\">\n<h1>TypeError</h1>\n<div class=\"detail\">\n  <p class=\"errormsg\">TypeError: Object of type WeiboRecord is not JSON serializable</p>\n</div>\n<h2 class=\"traceback\">Traceback <em>(most recent call last)</em></h2>\n<div class=\"traceback\">\n  \n  <ul><li><div class=\"frame\" id=\"frame-2455155536000\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2463</em>,\n      in <code class=\"function\">__call__</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def __call__(self, environ, start_response):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>WSGI application. This calls :meth:`wsgi_app` which can be</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>wrapped to applying middleware.&quot;&quot;&quot;</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.wsgi_app(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>def __repr__(self):</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>return &quot;&lt;%s %r&gt;&quot; % (self.__class__.__name__, self.name)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536168\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2449</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>return response(environ, start_response)</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>finally:</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536056\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask_cors\\extension.py\"</cite>,\n      line <em class=\"line\">161</em>,\n      in <code class=\"function\">wrapped_function</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span># Wrap exception handlers with cross_origin</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span># These error handlers will still respect the behavior of the route</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if options.get('intercept_exceptions', True):</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>def _after_request_decorator(f):</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>def wrapped_function(*args, **kwargs):</pre>\n<pre class=\"line current\"><span class=\"ws\">                    </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>return wrapped_function</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>if hasattr(app, 'handle_exception'):</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>app.handle_exception = _after_request_decorator(</pre>\n<pre class=\"line after\"><span class=\"ws\">                    </span>app.handle_exception)</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155539584\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1866</em>,\n      in <code class=\"function\">handle_exception</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span># if we want to repropagate the exception, we can attempt to</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># raise it with the whole traceback in case we can do that</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># (the function was actually called from the except part)</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span># otherwise, we just raise the error again</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if exc_value is e:</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>reraise(exc_type, exc_value, tb)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>raise e</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>self.log_exception((exc_type, exc_value, tb))</pre>\n<pre class=\"line after\"><span class=\"ws\">        </span>server_error = InternalServerError()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536112\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\_compat.py\"</cite>,\n      line <em class=\"line\">39</em>,\n      in <code class=\"function\">reraise</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">    </span>import collections.abc as collections_abc</pre>\n<pre class=\"line before\"><span class=\"ws\"></span> </pre>\n<pre class=\"line before\"><span class=\"ws\">    </span>def reraise(tp, value, tb=None):</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>if value.__traceback__ is not tb:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>raise value.with_traceback(tb)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>raise value</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>implements_to_string = _identity</pre>\n<pre class=\"line after\"><span class=\"ws\"></span> </pre>\n<pre class=\"line after\"><span class=\"ws\"></span>else:</pre>\n<pre class=\"line after\"><span class=\"ws\">    </span>iterkeys = lambda d: d.iterkeys()</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536392\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">2446</em>,\n      in <code class=\"function\">wsgi_app</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">        </span>ctx = self.request_context(environ)</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>error = None</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>try:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>ctx.push()</pre>\n<pre class=\"line current\"><span class=\"ws\">                </span>response = self.full_dispatch_request()</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except Exception as e:</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = e</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>response = self.handle_exception(e)</pre>\n<pre class=\"line after\"><span class=\"ws\">            </span>except:  # noqa: B001</pre>\n<pre class=\"line after\"><span class=\"ws\">                </span>error = sys.exc_info()[1]</pre></div>\n</div>\n\n<li><div class=\"frame\" id=\"frame-2455155536672\">\n  <h4>File <cite class=\"filename\">\"F:\\exerciseCode\\python\\flask-umi\\umi\\lib\\site-packages\\flask\\app.py\"</cite>,\n      line <em class=\"line\">1952</em>,\n      in <code class=\"function\">full_dispatch_request</code></h4>\n  <div class=\"source library\"><pre class=\"line before\"><span class=\"ws\">            </span>rv = self.preprocess_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>if rv is None:</pre>\n<pre class=\"line before\"><span class=\"ws\">                </span>rv = self.dispatch_request()</pre>\n<pre class=\"line before\"><span class=\"ws\">        </span>except Exception as e:</pre>\n<pre class=\"line before\"><span class=\"ws\">            </span>rv = self.handle_user_exception(e)</pre>\n<pre class=\"line current\"><span class=\"ws\">        </span>return self.finalize_request(rv)</pre>\n<pre class=\"l...(32732)","requestUrls":["http://localhost:5000/weibo/capture"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":5000,"socketHandledRequests":1,"socketHandledResponses":1}
pid: 6768
hostname: PC-201903022055

2019-11-25 16:02:40,020 ERROR 12784 nodejs.EADDRINUSEError: bind EADDRINUSE null:8000 (uncaughtException throw 1 times on pid:12784)
    at listenOnMasterHandle (net.js:1344:16)
    at shared (internal/cluster/child.js:120:3)
    at Worker.send (internal/cluster/child.js:91:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:194:15)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
errno: "EADDRINUSE"
code: "EADDRINUSE"
syscall: "bind"
address: null
port: 8000
name: "EADDRINUSEError"
pid: 12784
hostname: PC-201903022055

2019-11-25 16:04:56,689 ERROR 15808 nodejs.EADDRINUSEError: bind EADDRINUSE null:8001 (uncaughtException throw 1 times on pid:15808)
    at listenOnMasterHandle (net.js:1344:16)
    at shared (internal/cluster/child.js:120:3)
    at Worker.send (internal/cluster/child.js:91:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:194:15)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
errno: "EADDRINUSE"
code: "EADDRINUSE"
syscall: "bind"
address: null
port: 8001
name: "EADDRINUSEError"
pid: 15808
hostname: PC-201903022055

2019-11-25 16:05:49,801 ERROR 21852 nodejs.EADDRINUSEError: bind EADDRINUSE null:8001 (uncaughtException throw 1 times on pid:21852)
    at listenOnMasterHandle (net.js:1344:16)
    at shared (internal/cluster/child.js:120:3)
    at Worker.send (internal/cluster/child.js:91:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:194:15)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
errno: "EADDRINUSE"
code: "EADDRINUSE"
syscall: "bind"
address: null
port: 8001
name: "EADDRINUSEError"
pid: 21852
hostname: PC-201903022055

2019-11-27 10:52:36,421 ERROR 13084 nodejs.ReferenceError: action is not defined
    at app.ready (F:\exerciseCode\js\node\egg-example\app.js:15:22)
    at process.nextTick (F:\exerciseCode\js\node\egg-example\node_modules\get-ready\index.js:73:53)
    at process._tickCallback (internal/process/next_tick.js:61:11)

pid: 13084
hostname: PC-201903022055

2019-11-27 10:54:09,805 ERROR 12148 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 12148
hostname: PC-201903022055

2019-11-27 11:01:20,534 ERROR 12468 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 12468
hostname: PC-201903022055

2019-11-27 11:33:47,202 ERROR 12468 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 12468
hostname: PC-201903022055

2019-11-27 11:35:57,362 ERROR 12468 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 12468
hostname: PC-201903022055

2019-11-27 11:37:42,136 ERROR 12468 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 12468
hostname: PC-201903022055

2019-11-27 11:43:43,156 ERROR 15820 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 15820
hostname: PC-201903022055

2019-11-27 11:48:15,931 ERROR 14988 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 14988
hostname: PC-201903022055

2019-11-27 11:50:12,022 ERROR 16044 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 16044
hostname: PC-201903022055

2019-11-27 12:00:08,086 ERROR 16716 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 16716
hostname: PC-201903022055

2019-11-27 12:02:47,097 ERROR 16716 nodejs.unhandledExceptionError: ENOENT: no such file or directory, stat 'F:\exerciseCode\js\node\egg-example\app.js'
    at Object.statSync (fs.js:851:3)
    at DevelopmentEventSource._onFsWatchChange (F:\exerciseCode\js\node\egg-example\node_modules\egg-watcher\lib\event-sources\development.js:82:16)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
errno: -4058
syscall: "stat"
code: "ENOENT"
path: "F:\\exerciseCode\\js\\node\\egg-example\\app.js"
name: "unhandledExceptionError"
pid: 16716
hostname: PC-201903022055

2019-11-27 12:10:47,724 ERROR 15608 nodejs.ServerNoResponseError: server 127.0.0.1:56370 no response in 20003ms, maybe the socket is end on the other side. (address: 127.0.0.1:56370)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\tcp-base\lib\base.js:427:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ServerNoResponseError"
pid: 15608
hostname: PC-201903022055

2019-11-27 13:37:06,869 ERROR 20444 nodejs.ClusterClientNoResponseError: client no response in 125744ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 20444
hostname: PC-201903022055

2019-11-27 14:28:34,807 ERROR 17540 nodejs.TypeError: Cannot read property 'curl' of undefined
    at Messenger.agent.messenger.on (F:\exerciseCode\js\node\egg-example\agent.js:7:9)
    at Messenger.emit (events.js:189:13)
    at Messenger._onMessage (F:\exerciseCode\js\node\egg-example\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 17540
hostname: PC-201903022055

2019-11-27 14:31:32,884 ERROR 20352 nodejs.TypeError: Cannot read property 'curl' of undefined
    at Messenger.agent.messenger.on (F:\exerciseCode\js\node\egg-example\agent.js:7:9)
    at Messenger.emit (events.js:189:13)
    at Messenger._onMessage (F:\exerciseCode\js\node\egg-example\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 20352
hostname: PC-201903022055

2019-11-27 14:36:09,674 ERROR 18204 nodejs.TypeError: Cannot read property 'request' of undefined
    at Messenger.agent.messenger.on (F:\exerciseCode\js\node\egg-example\agent.js:24:19)
    at Messenger.emit (events.js:189:13)
    at Messenger._onMessage (F:\exerciseCode\js\node\egg-example\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 18204
hostname: PC-201903022055

2019-11-27 14:36:43,520 ERROR 20040 nodejs.TypeError: Cannot set property 'body' of undefined
    at Messenger.agent.messenger.on (F:\exerciseCode\js\node\egg-example\agent.js:19:16)
    at Messenger.emit (events.js:189:13)
    at Messenger._onMessage (F:\exerciseCode\js\node\egg-example\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 20040
hostname: PC-201903022055

2019-11-27 14:41:18,925 ERROR 2288 nodejs.ReferenceError: ctx is not defined
    at Messenger.agent.messenger.on.obj (F:\exerciseCode\js\node\egg-example\agent.js:19:7)
    at Messenger.emit (events.js:189:13)
    at Messenger._onMessage (F:\exerciseCode\js\node\egg-example\node_modules\egg\lib\core\messenger\ipc.js:116:12)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 2288
hostname: PC-201903022055

2019-11-27 15:19:11,869 ERROR 21256 nodejs.RequestError: connect ECONNREFUSED 127.0.0.1:5000, POST http://localhost:5000/weibo/capture -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"localhost:5000:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 5000
name: "RequestError"
data: undefined
path: "/weibo/capture"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":1018,"keepAliveSocket":false,"requestUrls":["http://localhost:5000/weibo/capture"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 21256
hostname: PC-201903022055

2019-11-27 15:19:52,452 ERROR 20676 nodejs.RequestError: connect ECONNREFUSED 127.0.0.1:5000, POST http://localhost:5000/weibo/capture -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"localhost:5000:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 5000
name: "RequestError"
data: undefined
path: "/weibo/capture"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":1019,"keepAliveSocket":false,"requestUrls":["http://localhost:5000/weibo/capture"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 20676
hostname: PC-201903022055

2019-11-27 15:45:46,826 ERROR 20972 nodejs.ResponseTimeoutError: Response timeout for 3000ms, POST http://localhost:5000/weibo/capture -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:940:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ResponseTimeoutError"
requestId: 2
data: undefined
path: "/weibo/capture"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":3004,"keepAliveSocket":false,"requestUrls":["http://localhost:5000/weibo/capture"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":5000,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 20972
hostname: PC-201903022055

2019-11-27 15:56:50,854 ERROR 20660 nodejs.ResponseTimeoutError: Response timeout for 3000ms, POST http://localhost:5000/weibo/capture -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (F:\exerciseCode\js\node\egg-example\node_modules\urllib\lib\urllib.js:940:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ResponseTimeoutError"
requestId: 1
data: undefined
path: "/weibo/capture"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":3042,"keepAliveSocket":false,"requestUrls":["http://localhost:5000/weibo/capture"],"timing":null,"remoteAddress":"127.0.0.1","remotePort":5000,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 20660
hostname: PC-201903022055

2019-11-29 13:37:50,614 ERROR 5996 nodejs.ClusterClientNoResponseError: client no response in 3698362ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 5996
hostname: PC-201903022055

2019-11-30 21:00:12,583 ERROR 1280 nodejs.ClusterClientNoResponseError: client no response in 2449224ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 1280
hostname: PC-201903022055

2019-12-01 21:36:51,058 ERROR 9268 nodejs.ClusterClientNoResponseError: client no response in 15747800ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (F:\exerciseCode\js\node\egg-example\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 9268
hostname: PC-201903022055

2019-12-04 11:14:45,663 ERROR 11696 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:11696)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 11696
hostname: PC-201903022055

2019-12-04 11:16:15,314 ERROR 12568 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12568)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12568
hostname: PC-201903022055

2019-12-04 11:16:16,907 ERROR 12568 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:12568)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12568
hostname: PC-201903022055

2019-12-04 11:16:45,592 ERROR 12928 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12928)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12928
hostname: PC-201903022055

2019-12-04 11:16:46,205 ERROR 12928 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:12928)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12928
hostname: PC-201903022055

2019-12-04 11:21:45,915 ERROR 10764 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:10764)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 10764
hostname: PC-201903022055

2019-12-04 11:21:47,065 ERROR 10764 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:10764)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 10764
hostname: PC-201903022055

2019-12-04 11:35:24,062 ERROR 12008 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12008)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12008
hostname: PC-201903022055

2019-12-04 11:35:25,367 ERROR 12008 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:12008)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12008
hostname: PC-201903022055

2019-12-04 11:36:18,883 ERROR 12316 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12316)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12316
hostname: PC-201903022055

2019-12-04 11:36:19,694 ERROR 12316 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:12316)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12316
hostname: PC-201903022055

2019-12-04 14:18:15,384 ERROR 1064 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:1064)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 1064
hostname: PC-201903022055

2019-12-04 14:18:17,037 ERROR 1064 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:1064)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 1064
hostname: PC-201903022055

2019-12-04 14:21:32,307 ERROR 11588 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 11588
hostname: PC-201903022055

2019-12-04 14:25:09,257 ERROR 12684 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12684)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12684
hostname: PC-201903022055

2019-12-04 15:07:51,691 ERROR 14864 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:14864)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14864
hostname: PC-201903022055

2019-12-04 15:07:52,946 ERROR 14864 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:14864)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14864
hostname: PC-201903022055

2019-12-04 15:09:29,983 ERROR 9240 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:9240)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 9240
hostname: PC-201903022055

2019-12-04 15:09:31,037 ERROR 9240 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:9240)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 9240
hostname: PC-201903022055

2019-12-04 15:16:14,328 ERROR 11836 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:11836)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 11836
hostname: PC-201903022055

2019-12-04 15:17:55,059 ERROR 12172 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12172)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12172
hostname: PC-201903022055

2019-12-04 15:19:03,385 ERROR 13320 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:13320)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 13320
hostname: PC-201903022055

2019-12-04 15:21:55,325 ERROR 14128 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:14128)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14128
hostname: PC-201903022055

2019-12-04 15:21:56,993 ERROR 14128 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:14128)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14128
hostname: PC-201903022055

2019-12-04 15:35:05,053 ERROR 14876 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:14876)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14876
hostname: PC-201903022055

2019-12-04 15:35:06,417 ERROR 14876 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:14876)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14876
hostname: PC-201903022055

2019-12-04 15:35:44,642 ERROR 10252 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:10252)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 10252
hostname: PC-201903022055

2019-12-04 15:35:45,540 ERROR 10252 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:10252)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 10252
hostname: PC-201903022055

2019-12-04 15:41:41,381 ERROR 14432 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:14432)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14432
hostname: PC-201903022055

2019-12-04 15:41:42,343 ERROR 14432 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:14432)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 14432
hostname: PC-201903022055

2019-12-04 15:43:19,411 ERROR 12772 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:12772)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12772
hostname: PC-201903022055

2019-12-04 15:43:21,255 ERROR 12772 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:12772)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 12772
hostname: PC-201903022055

2019-12-04 15:47:55,766 ERROR 9240 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:9240)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 9240
hostname: PC-201903022055

2019-12-04 15:47:55,811 ERROR 9240 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:9240)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 9240
hostname: PC-201903022055

2019-12-04 15:49:19,502 ERROR 13628 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 1 times on pid:13628)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 13628
hostname: PC-201903022055

2019-12-04 15:49:20,807 ERROR 13628 nodejs.TypeError: Cannot set property 'parsingHeadersStart' of undefined (uncaughtException throw 2 times on pid:13628)
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

pid: 13628
hostname: PC-201903022055

2019-12-04 17:30:44,588 ERROR 14636 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 14636
hostname: PC-201903022055

2019-12-04 17:30:44,878 ERROR 14636 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 14636
hostname: PC-201903022055

2019-12-04 17:30:45,202 ERROR 14636 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 14636
hostname: PC-201903022055

2019-12-04 17:35:46,842 ERROR 10564 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 10564
hostname: PC-201903022055

2019-12-04 17:35:47,004 ERROR 10564 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 10564
hostname: PC-201903022055

2019-12-04 17:35:47,410 ERROR 10564 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 10564
hostname: PC-201903022055

2019-12-05 09:33:42,780 ERROR 8828 nodejs.TypeError: app.redis.set is not a function
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:10:15
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 8828
hostname: PC-201903022055

2019-12-05 11:39:50,748 ERROR 14868 nodejs.TypeError: Cannot read property 'state' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:7:33
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 14868
hostname: PC-201903022055

2019-12-05 11:39:53,199 ERROR 14868 nodejs.TypeError: Cannot read property 'state' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:7:33
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 14868
hostname: PC-201903022055

2019-12-05 11:46:10,816 ERROR 15948 nodejs.TypeError: Cannot read property 'state' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:6:29
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 15948
hostname: PC-201903022055

2019-12-05 11:46:10,822 ERROR 15948 nodejs.TypeError: Cannot read property 'state' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:6:29
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 15948
hostname: PC-201903022055

2019-12-05 11:46:39,244 ERROR 11864 nodejs.TypeError: Cannot read property 'state' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:6:29
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 11864
hostname: PC-201903022055

2019-12-05 11:46:43,225 ERROR 11864 nodejs.TypeError: Cannot read property 'state' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:6:29
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 11864
hostname: PC-201903022055

2019-12-05 11:59:27,557 ERROR 13816 nodejs.TypeError: Cannot read property 'substring' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:14:27
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 13816
hostname: PC-201903022055

2019-12-05 11:59:27,814 ERROR 13816 nodejs.TypeError: Cannot read property 'substring' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:14:27
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 13816
hostname: PC-201903022055

2019-12-05 13:56:29,122 ERROR 15452 nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:17:65
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 15452
hostname: PC-201903022055

2019-12-05 13:59:34,740 ERROR 16104 nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:17:65
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 16104
hostname: PC-201903022055

2019-12-05 14:01:16,089 ERROR 15676 nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:18:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 15676
hostname: PC-201903022055

2019-12-06 09:05:19,637 ERROR 7352 [-/127.0.0.1/-/9ms GET /socket.io/?Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJbmZvIjp7ImlkIjoxLCJuYW1lIjoicm9vdCIsInBhc3N3b3JkIjoiMTIzNDU2Iiwic3RhdHVzIjoxLCJjcmVhY3RfdGltZSI6bnVsbCwidXBkYXRlX3RpbWUiOiIyMDE5LTEwLTMwIDE2OjA5OjIzLjc0NCJ9fSwiZXhwIjoxNTc1NTQwNDI0LCJpYXQiOjE1NzU1MzMyMjR9.FkyCRR4iKS7qaxuBPtSiDA30u8xfRn0FdPZH1V1eQnllzlAVoH1MxCyC9BJiVst_jecgO3I295itap_6IHxoo3_P7RO_GUvoBC_2IkBJ2QZunY0u0ytGIcdleXkMBpHE-0Nw770EffOVDcosOX_7OkCOnv87tCPZgkMTWQ-xEQc&EIO=3&transport=websocket] nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:19:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 7352
hostname: PC-201903022055

2019-12-07 09:17:13,921 ERROR 10572 [-/127.0.0.1/-/11ms GET /socket.io/?Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJbmZvIjp7ImlkIjoxLCJuYW1lIjoicm9vdCIsInBhc3N3b3JkIjoiMTIzNDU2Iiwic3RhdHVzIjoxLCJjcmVhY3RfdGltZSI6bnVsbCwidXBkYXRlX3RpbWUiOiIyMDE5LTEwLTMwIDE2OjA5OjIzLjc0NCJ9fSwiZXhwIjoxNTc1NjI1OTIyLCJpYXQiOjE1NzU2MTg3MjJ9.A6-1nniSq8JNCoyfXyJ71N7Zd4hkLOw_Fn5Bf8V9s5L0C6ugXY3UlTCJW1iWALZGg10DlvwbpwXZT94uGdQrah-uK8kVZ0bnyMDJlSfJCa9R5JM0MMG_94I3Zc5njoc9ARfLuY47ug53OLeJtqXP_e_hQ7FwG_BxDRWypx7wPjs&EIO=3&transport=websocket] nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:19:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 10572
hostname: PC-201903022055

2019-12-07 14:13:10,760 ERROR 13488 [-/127.0.0.1/-/12ms GET /socket.io/?Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJbmZvIjp7ImlkIjoxLCJuYW1lIjoicm9vdCIsInBhc3N3b3JkIjoiMTIzNDU2Iiwic3RhdHVzIjoxLCJjcmVhY3RfdGltZSI6bnVsbCwidXBkYXRlX3RpbWUiOiIyMDE5LTEwLTMwIDE2OjA5OjIzLjc0NCJ9fSwiZXhwIjoxNTc1Njg4NjQxLCJpYXQiOjE1NzU2ODE0NDF9.XQiQTrUCgQBflw-0kZt81f8yb1gQWU032WjjzxF0LW_sfjx7bRJB9Z85_5EQY7dLhNYAl-v19ms4ZT9Q-2IkK8-IsnOtp9Ff60pJsChRTad1CVj8dLM6CYCnm2WKu7Vo8obGsAOc817OACnKbQh2ryMSSiAaAN4S5A-YA56HPCQ&EIO=3&transport=websocket] nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:19:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 13488
hostname: PC-201903022055

2019-12-07 14:16:38,078 ERROR 13772 [-/127.0.0.1/-/145ms GET /socket.io/?Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJbmZvIjp7ImlkIjoxLCJuYW1lIjoicm9vdCIsInBhc3N3b3JkIjoiMTIzNDU2Iiwic3RhdHVzIjoxLCJjcmVhY3RfdGltZSI6bnVsbCwidXBkYXRlX3RpbWUiOiIyMDE5LTEwLTMwIDE2OjA5OjIzLjc0NCJ9fSwiZXhwIjoxNTc1Njg4NjQxLCJpYXQiOjE1NzU2ODE0NDF9.XQiQTrUCgQBflw-0kZt81f8yb1gQWU032WjjzxF0LW_sfjx7bRJB9Z85_5EQY7dLhNYAl-v19ms4ZT9Q-2IkK8-IsnOtp9Ff60pJsChRTad1CVj8dLM6CYCnm2WKu7Vo8obGsAOc817OACnKbQh2ryMSSiAaAN4S5A-YA56HPCQ&EIO=3&transport=websocket] nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:19:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 13772
hostname: PC-201903022055

2019-12-07 18:05:04,177 ERROR 10100 [-/127.0.0.1/-/18ms GET /socket.io/?Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJbmZvIjp7ImlkIjoxLCJuYW1lIjoicm9vdCIsInBhc3N3b3JkIjoiMTIzNDU2Iiwic3RhdHVzIjoxLCJjcmVhY3RfdGltZSI6bnVsbCwidXBkYXRlX3RpbWUiOiIyMDE5LTEwLTMwIDE2OjA5OjIzLjc0NCJ9fSwiZXhwIjoxNTc1NzA2Mzk2LCJpYXQiOjE1NzU2OTkxOTZ9.I1lc92ARsAdJemuqU8pSJjNqsg-sehmixSUIWR547DRIkkCp39W8s8R_LpR6FRRxlcfu_2VAQuCX6uczEZm5B5IjDOmX6LIrvmtY9w0CzIHnvqBI-hfDIFbyVaNTqxc5lrFzn777IO8SSotB9J199IF_RC8Qac3TlHlBAqoT-z4&EIO=3&transport=websocket] nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:19:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 10100
hostname: PC-201903022055

2019-12-09 13:59:22,914 ERROR 8988 [-/127.0.0.1/-/15ms GET /socket.io/?Authorization=Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJbmZvIjp7ImlkIjoxLCJuYW1lIjoicm9vdCIsInBhc3N3b3JkIjoiMTIzNDU2Iiwic3RhdHVzIjoxLCJjcmVhY3RfdGltZSI6bnVsbCwidXBkYXRlX3RpbWUiOiIyMDE5LTEwLTMwIDE2OjA5OjIzLjc0NCJ9fSwiZXhwIjoxNTc1NzIwNDk2LCJpYXQiOjE1NzU3MTMyOTZ9.iOUrzPJPXl_nr8o2O78Q8Vxcf5JAtk0gBVnf9FjygyNCTqhpz8eypcuZOmQ2fkfi8D4YkrdboJ_CjySZepyi7Erqz2P2lfx7fpZn1jsdp4eg2lPTvdzfGOMh1TjvEbEgXUp_0q1Qzw2FgZAYhZWHZChAs50ur0wn_ouTiWtjWds&EIO=3&transport=websocket] nodejs.TypeError: Cannot read property 'id' of undefined
    at F:\exerciseCode\js\node\egg-example\app\io\middleware\connection.js:19:67
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at session (F:\exerciseCode\js\node\egg-example\node_modules\koa-session\index.js:41:13)
    at dispatch (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:42:32)
    at F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\node_modules\koa-compose\index.js:34:12
    at module.exports (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\connectionMiddlewareInit.js:14:3)
    at Array.<anonymous> (F:\exerciseCode\js\node\egg-example\node_modules\egg-socket.io\lib\io.js:121:7)
    at run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (F:\exerciseCode\js\node\egg-example\node_modules\socket.io\lib\namespace.js:164:8)

pid: 8988
hostname: PC-201903022055

